#!/bin/bash

export PATH="${PATH}:/usr/ccs/bin:/usr/bin:/usr/sbin:/bin:/usr/sfw/bin:/usr/openwin/bin:/usr/X11R6/bin"

    exec_prefix=/usr
    PYTHONPATH=${PYTHONPATH}:${exec_prefix}/lib/python2.7/dist-packages
    export PYTHONPATH

    /usr/bin/python -c "import dbr.dbr"

